.TH fzputtygen 1 "January 2018" "" "TabFTP Manual"
.SH NAME
fzputtygen \- SFTP private key converter of TabFTP
.SH DESCRIPTION
.B fzputtygen
is part of TabFTP. It is used to convert private keys from OpenSSH or ssh.com format into a format understood by fzsftp. It usually gets called by TabFTP and is not intended to be used directly.
.P
.B fzputtygen
is based on the puttygen component of PuTTY.
.SH SUPPORT
Please visit the TabFTP project page for further information.
.SH COPYRIGHT
Copyright (C) 2004\-2018  Tim Kosse
.br
Copyright (C) 1997\-2018  Simon Tatham and the PuTTY team
.P
TabFTP is distributed under the terms of the GNU General Public License version 2 or later.
.SH "SEE ALSO"
tabftp(1)
